---
name: "test action: install specific version"
on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: "Check out repository"
      uses: actions/checkout@v3

    - name: Install Nhost CLI
      id: install-nhost-cli
      uses: ./
      with:
        version: 1.2.0

    - name: Verify version
      run: |
        installed_version=$(nhost --version | awk '{ print $3 }')
        if [ "$actual_version" != "1.2.0" ]; then
          echo "Versions do not match: installed_version=$installed_version, expected=1.2.0"
          exit 1
        fi
      shell: bash
